apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: acm-policies-create-infra-mcp
  namespace: custom-policies
  labels:
    subscription-pause: "false"
  annotations:
    apps.open-cluster-management.io/github-path: policies/create-infra-machine-config-pool/base
    apps.open-cluster-management.io/github-branch: create-infra-machine-config-pool
spec:
  channel: custom-policies/acm-gitops-github
  placement:
    local: true
